server/config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, path: :service, controllers: {
    sessions: 'service/devise/sessions',
    unlocks: 'service/devise/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :service do
    resources :categories
    resources :outcomes do
      collection do
        post :publish_all
      end
    end
    resources :users_outcomes, only: :index
    root 'home#index'
  end

  namespace :api, default: { format: :json } do
    resources :outcomes, only: [] do
      post :index, on: :collection
    end
    resources :reactions, only: :create
    resources :users_outcomes, only: [] do
      post :index, on: :collection
    end
    resources :users, only: :create
  end
end

server/app/models/users_outcome.rb
# == Schema Information
#
# Table name: users_outcomes
#
#  id         :bigint(8)        not null, primary key
#  post_date  :date             not null
#  post_time  :integer          not null
#  user_id    :bigint(8)        not null
#  outcome_id :bigint(8)        not null
#  reaction   :integer          not null
#  comment    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UsersOutcome < ApplicationRecord
  belongs_to :user
  belongs_to :outcome

  # TODO: enum :reaction
  PERMITTED_REACTIONS = [1, 2, 3, 4].freeze

  validates :post_date, presence: true
  validates :post_time, presence: true
  validates :reaction, presence: true, inclusion: { in: PERMITTED_REACTIONS }
  validates :outcome_id, uniqueness: { scope: %i[post_date post_time user_id] }
end

server/app/controllers/api/users_outcomes_controller.rb
module Api
  # 結果絞り込みAPI
  class UsersOutcomesController < ApiController
    include Api::UsersOutcomesMethods

    def index
      raise_api_error :invalid_param if params[:identifier].blank?
      raise_api_error :unreacted unless already_reacted?
      load_time
      load_users_outcomes
      load_data
      response_success @data
    end
  end
end

server/app/controllers/service/categories_controller.rb
module Service
  class CategoriesController < ServiceController
    def index
      @categories = Category.all.order(:display_order)
    end

    def show
      load_category
      redirect_to service_categories_path, alert: '見つかりません' unless @category
    end

    def new
      @category = Category.new
    end

    def edit
      load_category
      redirect_to service_categories_path, alert: '見つかりません' unless @category
    end

    def create
      @category = Category.new(category_params)
      return render :new unless @category.save
      redirect_to service_categories_path, notice: '作成されました'
    end

    def update
      load_category
      return redirect_to service_categories_path, alert: '見つかりません' unless @category
      @category.attributes = category_params
      return render :edit unless @category.save
      redirect_to service_category_path(@category), notice: '更新されました'
    end

    def destroy
      load_category
      return redirect_to service_categories_path, alert: '見つかりません' unless @category
      return redirect_to service_categories_path, alert: '公開中の「何した」が含まれるカテゴリは削除できません' if @category.published_outcomes?
      @category.destroy
      redirect_to service_categories_path, notice: '削除されました'
    end

    private

    def load_category
      @category = Category.find_by(id: params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :display_order)
    end
  end
end

server/app/controllers/service/home_controller.rb
module Service
  class HomeController < ServiceController
    def index; end
  end
end

server/app/controllers/service/outcomes_controller.rb
module Service
  class OutcomesController < ServiceController
    def index
      @outcomes = Outcome.all.order(:display_order, :category_id)
    end

    def show
      load_outcome
      redirect_to service_outcomes_path, alert: '見つかりません' unless @outcome
    end

    def new
      load_categories_selection
      @outcome = Outcome.new
    end

    def edit
      load_categories_selection
      load_outcome
      redirect_to service_outcomes_path, alert: '見つかりません' unless @outcome
    end

    def create
      @outcome = Outcome.new(outcome_params)
      unless @outcome.save
        load_categories_selection
        return render :new
      end
      redirect_to service_outcomes_path, notice: '作成されました'
    end

    def update
      load_outcome
      return redirect_to service_outcomes_path, alert: '見つかりません' unless @outcome
      @outcome.attributes = outcome_params
      unless @outcome.save
        load_categories_selection
        return render :edit
      end
      redirect_to service_outcome_path(@outcome), notice: '更新されました'
    end

    def destroy
      load_outcome
      return redirect_to service_outcomes_path, alert: '見つかりません' unless @outcome
      return redirect_to service_outcomes_path, alert: '公開中の「何した」は削除できません' if @outcome.published
      @outcome.destroy
      redirect_to service_outcomes_url, notice: '削除されました'
    end

    def publish_all
      return redirect_to service_outcomes_path, alert: 'チェックを入れてください' unless params[:publish]
      checked_data = params[:publish].keys
      checked_data.each(&method(:publish_outcome))
      redirect_to service_outcomes_path, notice: after_published_message
    end

    private

    def load_outcome
      @outcome = Outcome.find_by(id: params[:id])
    end

    def outcome_params
      params.require(:outcome).permit(:category_id, :name, :published, :display_order, :r_value, :g_value, :b_value)
    end

    def load_categories_selection
      @categories_selection = Category.pluck(:name, :id)
    end

    def publish_outcome(outcome_id)
      outcome = Outcome.find_by(id: outcome_id)
      return unless outcome
      outcome.update published: params[:unpublish].blank?
    end

    def after_published_message
      params[:unpublish].blank? ? '一括公開しました' : '一括非公開しました'
    end
  end
end

server/app/controllers/service/service_controller.rb
module Service
  class ServiceController < ApplicationController
    before_action :authenticate_administrator!

    layout 'service/service'
  end
end

server/app/controllers/service/users_outcomes_controller.rb
module Service
  class UsersOutcomesController < ServiceController
    def index
      load_users_outcomes
      load_outcomes
      load_comments
    end

    private

    def load_users_outcomes
      @q = UsersOutcome.includes(:outcome).search(params[:q])
      users_outcomes = @q.result
                         .select('users_outcomes.outcome_id, users_outcomes.reaction, COUNT(*) AS cnt')
                         .group(:outcome_id, :reaction)
                         .order(:outcome_id, :reaction)
                         .to_a
      @users_outcomes = users_outcomes.group_by(&:outcome_id)
    end

    def load_outcomes
      @all_outcome_names = Outcome.select(:id, :name)
    end

    def load_comments
      all_comments = @q.result
      all_comments = all_comments.where.not(comment: nil) if params[:show_no_comment].present?
      comments = all_comments.includes(:user).order(id: :desc).limit(1000).to_a
      @comments = comments.group_by(&:outcome_id)
    end
  end
end

server/app/helpers/service/outcomes_helper.rb
module Service
  module OutcomesHelper
  end
end

server/app/views/service/users_outcomes/index.html.slim
- @title = '統計データ確認'
p#notice = notice
p#alert = alert

= search_form_for @q, url: service_users_outcomes_path, method: :get do |f|
  table.table-striped
    tbody
      tr
        td 「何した」
        td
          - selected_outcome_ids = @users_outcomes.map { |outcome_id, _| outcome_id}.uniq
          =  f.collection_check_boxes :outcome_id_in, @all_outcome_names, :id, :name do |b|
            - b.label do
              = b.check_box
              - if b.value.in? selected_outcome_ids
                = link_to(b.text, "#outcome_#{b.value}")
              - else
                = b.text
      tr
        td 投稿日
        td = f.text_field :post_date_eq, class: 'date-picker'
      tr
        td 投稿時間帯（From）
        td = f.select :post_time_gteq, 0..23, include_blank: true
      tr
        td 投稿時間帯（To）
        td = f.select :post_time_lteq, 0..23, include_blank: true
      tr
        td ノーコメントを非表示
        / td = f.check_box :comment_not_null
        / ↑このやり方では IS NULL と IS NOT NULL のいずれかしか選択できないため、個別実装
        td = check_box_tag :show_no_comment, nil, params[:show_no_comment].present?
      tr
        td = f.submit '検索'
        td

- @users_outcomes.each do |outcome_id, users_outcomes|
  h2[id="outcome_#{users_outcomes.first&.outcome_id}"]
    = users_outcomes.first&.outcome.name
  - all_count = users_outcomes.sum(&:cnt)
  table.table-striped
    thead
      tr.table-success
        th リアクション
        th 人数
        th %
    tbody
      - users_outcomes.each do |users_outcome|
        tr
          td = users_outcome.reaction
          td = users_outcome.cnt
          td = all_count.zero? ? '0.0' : format('%.1f', Rational(users_outcome.cnt * 100, all_count))
      tr
        td 合計
        td = all_count
        td = all_count.zero? ? '0.0' : '100.0'

  h3 直近のコメント
  table.table-striped
    thead
      tr.table-success
        th #
        th ユーザID
        th 性別
        th 年齢
        th 都道府県
        th リアクション
        th コメント
        th 投稿日時
    tbody
      - @comments[outcome_id]&.take(30)&.each&.with_index(1) do |comment, i|
        - user = comment.user
        tr
          td = i
          td = user.id
          td = user.gender_i18n
          td = user.age
          td = user.prefecture_i18n
          td = comment.reaction
          td = comment.comment
          td = comment.created_at&.strftime('%Y-%m-%d %H:%M:%S')