server/config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, path: :service, controllers: {
    sessions: 'service/devise/sessions',
    unlocks: 'service/devise/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :service do
    resources :categories
    resources :outcomes do
      collection do
        post :publish_all
      end
    end
    resources :users_outcomes, only: :index
    root 'home#index'
  end

  namespace :api, default: { format: :json } do
    resources :outcomes, only: [] do
      post :index, on: :collection
    end
    resources :reactions, only: :create
    resources :users_outcomes, only: [] do
      post :index, on: :collection
    end
    resources :users, only: :create
  end
end

server/app/models/outcome.rb
# == Schema Information
#
# Table name: outcomes
#
#  id            :bigint(8)        not null, primary key
#  category_id   :integer          not null
#  name          :string           not null
#  published     :boolean          default(FALSE), not null
#  display_order :integer          default(0), not null
#  r_value       :integer          default(255), not null
#  g_value       :integer          default(255), not null
#  b_value       :integer          default(255), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Outcome < ApplicationRecord
  belongs_to :category

  validates :name, presence: true, uniqueness: true
  validates :r_value, :g_value, :b_value,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 255 }

  scope :published, -> { where published: true }

  # 色プレビュー（HTML用）
  def color_preview(with_prefix = true)
    prefix = '#' if with_prefix
    [
      prefix,
      format('%02x', r_value),
      format('%02x', g_value),
      format('%02x', b_value)
    ].join
  end
end

server/app/controllers/api/outcomes_controller.rb
module Api
  # 選択可能アクション取得API
  class OutcomesController < ApiController
    def index
      raise_api_error :invalid_param if params[:identifier].blank?
      raise_api_error :already_reacted if already_reacted?

      response_success outcomes
    end

    private

    def outcomes
      Outcome.published.order(:display_order).map do |outcome|
        { name: outcome.name, id: outcome.id, r: outcome.r_value, g: outcome.g_value, b: outcome.b_value }
      end
    end
  end
end

server/app/controllers/service/categories_controller.rb
module Service
  class CategoriesController < ServiceController
    def index
      @categories = Category.all.order(:display_order)
    end

    def show
      load_category
      redirect_to service_categories_path, alert: '見つかりません' unless @category
    end

    def new
      @category = Category.new
    end

    def edit
      load_category
      redirect_to service_categories_path, alert: '見つかりません' unless @category
    end

    def create
      @category = Category.new(category_params)
      return render :new unless @category.save
      redirect_to service_categories_path, notice: '作成されました'
    end

    def update
      load_category
      return redirect_to service_categories_path, alert: '見つかりません' unless @category
      @category.attributes = category_params
      return render :edit unless @category.save
      redirect_to service_category_path(@category), notice: '更新されました'
    end

    def destroy
      load_category
      return redirect_to service_categories_path, alert: '見つかりません' unless @category
      return redirect_to service_categories_path, alert: '公開中の「何した」が含まれるカテゴリは削除できません' if @category.published_outcomes?
      @category.destroy
      redirect_to service_categories_path, notice: '削除されました'
    end

    private

    def load_category
      @category = Category.find_by(id: params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :display_order)
    end
  end
end

server/app/controllers/service/home_controller.rb
module Service
  class HomeController < ServiceController
    def index; end
  end
end

server/app/controllers/service/outcomes_controller.rb
module Service
  class OutcomesController < ServiceController
    def index
      @outcomes = Outcome.all.order(:display_order, :category_id)
    end

    def show
      load_outcome
      redirect_to service_outcomes_path, alert: '見つかりません' unless @outcome
    end

    def new
      load_categories_selection
      @outcome = Outcome.new
    end

    def edit
      load_categories_selection
      load_outcome
      redirect_to service_outcomes_path, alert: '見つかりません' unless @outcome
    end

    def create
      @outcome = Outcome.new(outcome_params)
      unless @outcome.save
        load_categories_selection
        return render :new
      end
      redirect_to service_outcomes_path, notice: '作成されました'
    end

    def update
      load_outcome
      return redirect_to service_outcomes_path, alert: '見つかりません' unless @outcome
      @outcome.attributes = outcome_params
      unless @outcome.save
        load_categories_selection
        return render :edit
      end
      redirect_to service_outcome_path(@outcome), notice: '更新されました'
    end

    def destroy
      load_outcome
      return redirect_to service_outcomes_path, alert: '見つかりません' unless @outcome
      return redirect_to service_outcomes_path, alert: '公開中の「何した」は削除できません' if @outcome.published
      @outcome.destroy
      redirect_to service_outcomes_url, notice: '削除されました'
    end

    def publish_all
      return redirect_to service_outcomes_path, alert: 'チェックを入れてください' unless params[:publish]
      checked_data = params[:publish].keys
      checked_data.each(&method(:publish_outcome))
      redirect_to service_outcomes_path, notice: after_published_message
    end

    private

    def load_outcome
      @outcome = Outcome.find_by(id: params[:id])
    end

    def outcome_params
      params.require(:outcome).permit(:category_id, :name, :published, :display_order, :r_value, :g_value, :b_value)
    end

    def load_categories_selection
      @categories_selection = Category.pluck(:name, :id)
    end

    def publish_outcome(outcome_id)
      outcome = Outcome.find_by(id: outcome_id)
      return unless outcome
      outcome.update published: params[:unpublish].blank?
    end

    def after_published_message
      params[:unpublish].blank? ? '一括公開しました' : '一括非公開しました'
    end
  end
end

server/app/controllers/service/service_controller.rb
module Service
  class ServiceController < ApplicationController
    before_action :authenticate_administrator!

    layout 'service/service'
  end
end

server/app/controllers/service/users_outcomes_controller.rb
module Service
  class UsersOutcomesController < ServiceController
    def index
      load_users_outcomes
      load_outcomes
      load_comments
    end

    private

    def load_users_outcomes
      @q = UsersOutcome.includes(:outcome).search(params[:q])
      users_outcomes = @q.result
                         .select('users_outcomes.outcome_id, users_outcomes.reaction, COUNT(*) AS cnt')
                         .group(:outcome_id, :reaction)
                         .order(:outcome_id, :reaction)
                         .to_a
      @users_outcomes = users_outcomes.group_by(&:outcome_id)
    end

    def load_outcomes
      @all_outcome_names = Outcome.select(:id, :name)
    end

    def load_comments
      all_comments = @q.result
      all_comments = all_comments.where.not(comment: nil) if params[:show_no_comment].present?
      comments = all_comments.includes(:user).order(id: :desc).limit(1000).to_a
      @comments = comments.group_by(&:outcome_id)
    end
  end
end

server/app/helpers/service/outcomes_helper.rb
module Service
  module OutcomesHelper
  end
end

server/app/views/service/outcomes/_form.html.slim
= form_for @outcome, url: request_url do |f|
  - if @outcome.errors.any?
    #error_explanation
      h2 = 'エラーがあります'
      ul
        - @outcome.errors.full_messages.each do |message|
          li = message
  = f.label :category
  = f.select :category_id, @categories_selection

  = f.label :name
  = f.text_field :name

  = f.label :display_order
  = f.number_field :display_order

  = f.label :published
  = f.check_box :published

  = f.label :r_value
  = f.number_field :r_value

  = f.label :g_value
  = f.number_field :g_value

  = f.label :b_value
  = f.number_field :b_value

  .actions = f.submit class: 'btn btn-outline-warning'

server/app/views/service/outcomes/edit.html.slim
- @title = '何した編集'

= render 'form', request_url: service_outcome_path(@outcome)

= link_to '詳細', service_outcome_path(@outcome), class: 'btn btn-outline-info'
'
= link_to '戻る', service_outcomes_path, class: 'btn btn-outline-secondary'

server/app/views/service/outcomes/index.html.slim
- @title = '何した一覧'
p#notice = notice
p#alert = alert

= link_to '新規登録', new_service_outcome_path, class: 'btn btn-info'
= form_tag publish_all_service_outcomes_path do
  table.table-striped.mx-auto.container
    thead
      tr.table-success
        th
        th.text-center = t('activerecord.attributes.outcome.category')
        th.text-center = t('activerecord.attributes.outcome.name')
        th.text-center = t('activerecord.attributes.outcome.published')
        th.text-center = t('activerecord.attributes.outcome.display_order')
        th.text-center = t('activerecord.attributes.outcome.r_value')
        th.text-center = t('activerecord.attributes.outcome.g_value')
        th.text-center = t('activerecord.attributes.outcome.b_value')
        th.text-center = t('activerecord.attributes.outcome.color_preview')
        th
        th
        th

    tbody
      - @outcomes.each do |outcome|
        tr
          td = check_box_tag "publish[#{outcome.id}]", outcome.id, nil, class: :publish_all_class
          td = outcome.category&.name
          td = outcome.name
          - published_mark = outcome.published ? 'check_mark.png' : 'uncheck_mark.png'
          td = image_tag published_mark, class: 'publish-mark'
          td.text-center = outcome.display_order
          td.text-center = outcome.r_value
          td.text-center = outcome.g_value
          td.text-center = outcome.b_value
          td.text-center
            span style="background:#{outcome.color_preview}"
              | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          td = link_to '詳細', service_outcome_path(outcome), class: 'btn btn-outline-info'
          td = link_to '編集', edit_service_outcome_path(outcome), class: 'btn btn-outline-secondary'
          td = link_to '削除', service_outcome_path(outcome), class: 'btn btn-outline-danger', data: { confirm: '本当に削除しますか' }, method: :delete unless outcome.published

  br
  = submit_tag '一括公開', disabled: true, class: 'publish_all_button btn btn-outline-secondary'
  | &nbsp;
  = submit_tag '一括非公開', name: :unpublish, disabled: true, class: 'publish_all_button btn btn-outline-secondary'

server/app/views/service/outcomes/new.html.slim
- @title = '何した新規登録'

= render 'form', request_url: service_outcomes_path

= link_to '戻る', service_outcomes_path

server/app/views/service/outcomes/show.html.slim
p#notice = notice

table
  tbody
    tr
      td = t('activerecord.attributes.outcome.category')
      td = @outcome.category&.name
    tr
      td = t('activerecord.attributes.outcome.name')
      td = @outcome.name
    tr
      td = t('activerecord.attributes.outcome.display_order')
      td = @outcome.display_order
    tr
      td = t('activerecord.attributes.outcome.published')
      - published_mark = @outcome.published ? 'check_mark.png' : 'uncheck_mark.png'
      td = image_tag published_mark, class: 'publish-mark'
    tr
      td = t('activerecord.attributes.outcome.r_value')
      td = @outcome.r_value
    tr
      td = t('activerecord.attributes.outcome.g_value')
      td = @outcome.g_value
    tr
      td = t('activerecord.attributes.outcome.b_value')
      td = @outcome.b_value
    tr
      td = t('activerecord.attributes.outcome.color_preview')
      td
        span style="background:#{@outcome.color_preview}"
          | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

= link_to '編集', edit_service_outcome_path(@outcome)
'
= link_to '戻る', service_outcomes_path